version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./logs:/app/logs
      - ~/.kube/config:/root/.kube/config
    restart: unless-stopped

volumes:
  logs: