name: Lint & Security Check (Shell)

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: l0o0/bash-scan-action@v1
        with:
          files: shell/stress_test.sh

  action-bash-boilerplate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run boilerplate security check
        uses: reviewdog/action-bash-boilerplate@v1
        with:
          report-warnings: true