name: Update README on Main Commit

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate README stats
        run: |
          echo "[AUTO] Last updated: $(date)" > tmp_stats.md
          echo "" >> tmp_stats.md
          echo "## 🧪 Пример вывода:" >> tmp_stats.md
          echo "\`\`\`bash" >> tmp_stats.md
          head -n 20 shell/stress_test.sh | tail -n 10 >> tmp_stats.md
          echo "\`\`\`" >> tmp_stats.md

      - name: Replace section in README
        uses: joesontech/replace-text@v1
        with:
          file-path: README.md
          match-text: "## 🧪 Пример вывода:\n.*\n.*\n.*\n.*\n.*\n.*"
          replace-text: "$(cat tmp_stats.md)"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "docs: обновлен пример вывода"
          git push origin main